# Site settings
title: JUMPðŸ‹WHALE
description: >
  jump0whale ë¸”ë¡œê·¸
url: "https://jump0whale.github.io"

# URL ê·œì¹™
permalink: none

paginate: 8
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate